version: '3.1'

services:

  grocery_app:
    image: grocery_app
    container_name: grocery_app
    restart: always
    ports:
     - 8082:8080
    depends_on:
     - grocery_db
  grocery_db:
    image: centos_postgres:v1        
    container_name: grocery_db 
    volumes:
     - /data/postgres-data:/var/lib/postgresql/data
    ports:
     - 5431:5432       


         
