version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.8.15
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-network
    environment:
      - discovery.type=single-node
       
  
  kibana:
    image: kibana:6.8.15
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elasticsearch-network
    depends_on:
      - elasticsearch
 
networks:
  elasticsearch-network:         
       
     
