version: '3'

services:
 db:
   image: postgres
   restart: always
   ports:
    - 5431:5432
   volumes:
    - ./postgres-data:/var/lib/postgresql/data
   environment:
    POSTGRES_PASSWORD: postgres
   

#ENTRYPOINT[]
     
       


